config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'checkout', to: 'checkouts#show'
  post 'checkout/create', to: 'checkouts#create'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'products#index'
  # Defines the root path route ("/")
  authenticated :user, ->(user) { user.is_admin? } do
    root to: "admin/products#index", as: :admin_root
  end

  authenticated :user, ->(user) { user.is_user? } do
    root to: "products#index", as: :user_root
  end

  scope module: 'admin', path: 'admin' do
    # get 'products' => 'products#index'
    # patch "products/update" => "products#update", as: :admin_products_update
    resources :products
  end
  # resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, :description, :price, presence: true
    has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  has_many :products

  def is_admin?
    self.user_type == "admin"
  end

  def is_user?
    self.user_type == "user"
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product, only: %i[ show edit update destroy ]

    def index
            @products = Product.all
        end
    
    def show
    end

    def new
        @product = Product.new
    end

    def edit
    end

    def create
        @product = Product.new(product_params)
        # binding.pry

        # file_name = params[:product][:images].original_name.split('.').[0]
        # if params[:product][:images].present?
        #   image = {
        #     io: params[:product][:images],
        #     content_type: 'image/jpg',
        #     filename: file_name,
        #     key:"#{file_name +'-'+Time.zone.now.to_s}"
        #   }
        #   @product.images.attach(image)
        # end
        respond_to do |format|
            if @product.save
                format.html{ redirect_to products_path, notice: "Product was successfully created"}
            else
                format.html{ render :new, status: :unprocessable_entity}
            end
        end
    end

    def update
        respond_to do |format|
            if @product.update(product_params)
              format.html { redirect_to products_path, notice: "Product was successfully updated." }
            else
              format.html { render :edit, status: :unprocessable_entity }
            end
          end
    end

    def destroy
        @product.destroy
    
        respond_to do |format|
          format.html { redirect_to products_path, notice: "Products was successfully destroyed." }
        end
      end

    def delete_image_attachment
        @image = ActiveStorage::Blob.find_signed(params[:id])
        @image.attachments.first.purge
        redirect_back(fallback_location: edit_product_path)
    end

    private

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:name, :description, :price, :images => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def create
        product = Product.find(params[:id])
        @session = Stripe::Checkout::Session.create({
        payment_method_types: ['card'],
        line_items: [{
        price_data: {
            currency: 'inr',
            product_data: {
            name: product.name,
            },
            unit_amount: product.price*100,
        },
        quantity: 1,
        }],
        mode: 'payment',
        success_url: root_url,
        cancel_url: root_url,
        })
        redirect_to @session.url, allow_other_host: true 
    end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController

    def show
        current_user.set_payment_processor :stripe
        current_user.payment_processor.customer

        @checkout_session = current_user
            .payment_processor
            .checkout(
                mode: 'payment',
                line_items: 'price_1Ml5LcSAbUh3InK3bo5T8XBZ'
            )
    end

    def create
        product = Product.find(params[:id])
        @session = Stripe::Checkout::Session.create({
        payment_method_types: ['card'],
        line_items: [{
        price_data: {
            currency: 'inr',
            product_data: {
            name: product.name,
            description: product.description,
            },
            unit_amount: product.price*100,
        },
        quantity: 1,
        }],
        mode: 'payment',
        success_url: root_url,
        cancel_url: root_url,
        })
        redirect_to @session.url, allow_other_host: true 
    end

    def success
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    def index
        @products = Product.all
    end
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<% if @product.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li style="list-style-type: none; margin-left: -1rem;">
          <span class="badge badge-sm bg-gradient-danger"><%= message %></span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group mb-3">
  <div class="aestric-container mb-2">
    <%= f.label :name %><span class="aestric-color">*</span>
  </div>
  <%= f.text_field :name, class: "form-control form-control-lg", placeholder: "Name", required: true %>
</div>

<div class="form-group mb-3">
  <div class="aestric-container mb-2">
    <%= f.label :description %><span class="aestric-color">*</span>
  </div>
  <%= f.text_area :description, class: "form-control form-control-sm", placeholder: "Description", required: true %>
</div>

<div class="form-group mb-3">
  <div class="aestric-container mb-2">
    <%= f.label :price %><span class="aestric-color">*</span>
  </div>
  <%= f.number_field :price, class: "form-control", placeholder: "₹Price", required: true %>
</div>

<div class="form-group mb-3">
  <div class="aestric-container mb-2">
    <%= f.label :images, for:"formFileMultiple" %> <span class="aestric-color">*</span>
  </div>
  <%= f.file_field :images, class: "form-control", :multiple => true, id:"formFileMultiple"%><br>
</div>

<% if action_name == "edit" || action_name == "update" %>
  <%= f.submit "Update Product",  data: { confirm: 'Are you sure you have to update this?' }, class: "btn btn-primary mr-2" %>
<% else %>
  <%= f.submit "Create Product", class: "btn btn-primary mr-2" %>
<% end %>

app/views/admin/products/edit.html.erb
<%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
<div class="container-fluid pt-2">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= products_path %>">Products</a></li>
    <li class="breadcrumb-item active" aria-current="page">Edit</li>
  </ol>
</nav>
</div>
<div class="container-fluid pt-2">
  <div class="row">
    <div class="col-lg-6 grid-margin stretch-card">
      <div class="card">
        <div class="d-flex flex-column justify-content-center align-items-center form-contain">
        <%= link_to products_path, style:"width: 100%;" do %>
          <i class="fa fa-arrow-left"></i>
        <% end %>
          <div class="logo-container">
            <%= image_tag "dreamday.jpg", width: "100%", height: "50px", class: "mr-2", alt: "logo" %>
          </div>
        </div>
        <div class="card-body pt-2">
          <%= form_with(model: @product, local: true, class: "forms-sample") do |f| %>
            <%= render 'admin/products/form', f: f %>
          <% end %>  
        </div>
      </div>
    </div>
    <div class="col-md-6 card-body">
      <div class="text-muted">
        <p class="text-right">Updated on: <%= @product.updated_at.ctime.to_s %></p>
      </div>
      <div class="my-2">
        <% if @product.images.attached? %>
          <h6>Attached Media</h6>
          <div class="d-flex flex-wrap justify-content-center align-items-center">
            <% @product.images.each do |image| %>
              <div class="edit-form-attachment m-4">
                <%= image_tag image, :class => 'edit-form-img' %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container-fluid">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><% notice %></p>
  <% end %>

  <div class="card card-head mt-2">
    <div class="container-fluid flex justify-between items-center mb-2 mt-2">
      <h2 class="font-bold text-4xl" style="text-align:center">Products</h2>
      <%= link_to 'New Product',  new_product_path, class: "btn btn-outline-primary" %>
    </div>
  </div>
  
  <div class="card">
    <div class="card-body">
      <div id="products" class="min-w-full">
        <%= render 'layouts/product' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container-fluid pt-2">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="<%= products_path %>">Products</a></li>
      <li class="breadcrumb-item active" aria-current="page">New</li>
    </ol>
  </nav>
</div>

<div class="container-fluid pt-2">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="d-flex flex-column justify-content-center align-items-center form-contain">
        <%= link_to products_path, style:"width: 100%;" do %>
          <i class="fa fa-arrow-left"></i>
        <% end %>
        <div class="logo-container">
          <%= image_tag "dreamday.jpg", width: "100%", height: "50px", class: "mr-2", alt: "logo" %>
        </div>
      </div>
      <div class="card-body pt-2">
        <%= form_with(model: @product, local: true, class: "forms-sample") do |f| %>
          <%= render 'admin/products/form', f: f %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/checkouts/create.js.erb
var stripe = Stripe(ENV[STRIPE_SK])

stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then(function (result) {
    console.log(result.error_message)
});

app/views/checkouts/show.html.erb
<h1>Checkout!</h1>

<%= render partial:'pay/stripe/checkout_button', locals: {
    session: @checkout_session,
    title: "Buy" 
} %>

app/views/checkouts/success.html.erb
<div class="container">
   <div class="row">
      <div class="col-md-6 mx-auto mt-5">
         <div class="payment">
            <div class="payment_header">
               <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
            </div>
            <div class="content">
               <h1>Payment Success !</h1>
               <p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. </p>
               <a href="#">Go to Home</a>
            </div>
            
         </div>
      </div>
   </div>
</div>

app/views/layouts/_product.html.erb
<div class="container">
  <div class="row">
  <% @products.each do |product| %>
    <div class="col-md-6 card-body cont">
      <h5 class="card-title"><%= product.name%></h5>
      <p class="card-text"><strong class="block font-medium mb-1">Description:</strong> "<%= product.description %>"</p>  

      <p class="card-text"><strong class="block font-medium mb-1">Price:</strong>₹<%= product.price.to_f %></p> 
      <div>
        <%= button_to "Buy", checkout_create_path, params: {id: product.id}, remote: true%> <span><a href="#" class="btn btn-outline-info">Save this</a></span>
      </div>
      <div>
        <% if current_user.is_admin? %>
          <% if action_name != "show" %>
            <p><%= button_to "Destroy this product", product_path(product), method: :delete, class: "btn btn-secondary" %></p>
            <p><%= link_to 'Edit this product', edit_product_path(product), class: "btn btn-info" %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6 card-body cont">
      <div class="text-muted">
        <p class="text-right">Updated on: <%= product.updated_at.ctime.to_s %></p>
      </div>
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% if product.images.attached?%>
            <div class="carousel-item active">
              <%= image_tag product.images.first, width:100 %>
            </div>
            <% product.images.drop(1).each do |image| %>
              <div class="carousel-item">
                <%= image_tag image, width:100 %>
              </div>
            <% end %>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  <% end%>
  </div>
</div>

app/views/layouts/_top_nav_bar.html.erb
<%= stylesheet_link_tag "nav_bar" %>
<nav class="navbar navbar-expand-sm navbar-light px-4 sticky-top">
  <div class="navbar-brand">
    <a href="http://localhost:3000/admin/products">
      <%= image_tag "dreamday.jpg", width: "100%", height: "34px", class: "mr-2", alt: "logo" %>
    </a>
  </div>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse navigation" id="navbarToggleExternalContent">
    <ul class="navbar-nav ml-auto align-items-sm-center">
      <li class="nav-item m-1 mx-sm-2">
        <div class="username-holder">
          <% if current_user %>
          <div class="d-flex justify-content-start align-items-center text-dark">
            <i class="fa fa-user-circle"></i>
            <p class="text-capitalize m-1 ml-2 font-weight-bold"><%= current_user.name %></p>
          </div>
          <% end %>
        </div>
      </li>

      <li class="nav-item m-1 mx-sm-2">
        <% if user_signed_in? %>
          <span><%= button_to "logout", destroy_user_session_path, class:"bi bi-box-arrow-in-left btn btn-danger btn-sm shadow-none", method: :delete %></span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "admin-page", "data-turbo-track": "reload" %>
  </head>

  <body style="background-color:whitesmoke">
    <%= render "/layouts/top_nav_bar"%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><% notice %></p>
    <% end %>

    <div class="flex justify-between items-center">
      <h2 class="font-bold text-4xl" style="text-align:center">Products</h2>
    </div>
    <div class="card">
      <div class="card-body">
        <div id="products" class="min-w-full">
          <%= render 'layouts/product' %>
        </div>
      </div>
    </div>
  </div>
</div>